### ISSUE TITLE
deprecation warning on node 7+

### ISSUE THREAD

**Issue by zandzpider** [feross/parse-torrent#42]
node --harmony-async-await --trace-deprecation server

(node:39413) DeprecationWarning: Using Buffer without `new` will soon stop working. Use `new Buffer()`, or preferably `Buffer.from()`, `Buffer.allocUnsafe()` or `Buffer.alloc()` instead.
    at Buffer (buffer.js:79:13)
    at [snip snip]/node_modules/parse-torrent/index.js:109:17
    at Object.<anonymous> ([snip snip]/node_modules/parse-torrent/index.js:109:29)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)

**Comment by feross** [comment]
Update your version of Node.js to the latest v7.x. This deprecation warning was removed in the latest version.
